// Generated by PDF → React Design Grid Asset Builder
//
// Generated from:
// folio_spreads.pdf
//
// Project ID:
// 18

import React, { forwardRef, useMemo, useState } from 'react'

const GROUPS = [
  {
    "label": "Page 1",
    "items": [
      {
        "title": "Page 1 image 1",
        "ratio": 1.3772,
        "grid": "images/gallery/print-editorial/grid/page_1_image_1.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_1.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_1.webp"
      },
      {
        "title": "Page 1 image 2",
        "ratio": 0.735,
        "grid": "images/gallery/print-editorial/grid/page_1_image_2.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_2.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_2.webp"
      },
      {
        "title": "Page 1 image 3",
        "ratio": 0.7366,
        "grid": "images/gallery/print-editorial/grid/page_1_image_3.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_3.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_3.webp"
      },
      {
        "title": "Page 1 image 4",
        "ratio": 1.6982,
        "grid": "images/gallery/print-editorial/grid/page_1_image_4.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_4.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_4.webp"
      },
      {
        "title": "Page 1 image 5",
        "ratio": 1.491,
        "grid": "images/gallery/print-editorial/grid/page_1_image_5.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_5.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_5.webp"
      },
      {
        "title": "Page 1 image 6",
        "ratio": 0.6992,
        "grid": "images/gallery/print-editorial/grid/page_1_image_6.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_6.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_6.webp"
      },
      {
        "title": "Page 1 image 7",
        "ratio": 0.7125,
        "grid": "images/gallery/print-editorial/grid/page_1_image_7.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_7.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_7.webp"
      },
      {
        "title": "Page 1 image 8",
        "ratio": 1.4949,
        "grid": "images/gallery/print-editorial/grid/page_1_image_8.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_8.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_8.webp"
      },
      {
        "title": "Page 1 image 9",
        "ratio": 0.7191,
        "grid": "images/gallery/print-editorial/grid/page_1_image_9.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_9.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_9.webp"
      },
      {
        "title": "Page 1 image 10",
        "ratio": 2.2339,
        "grid": "images/gallery/print-editorial/grid/page_1_image_10.webp",
        "full": "images/gallery/print-editorial/full/page_1_image_10.jpg",
        "thumb": "images/gallery/print-editorial/thumbs/page_1_image_10.webp"
      }
    ]
  }
]

export const DESIGN_EXAMPLES_GROUPS = GROUPS

export const DesignExamplesSection = forwardRef(function DesignExamplesSection(
  { project, index, total, isActive },
  ref
) {
  const [activeGroup, setActiveGroup] = useState(0)
  const [activeItem, setActiveItem] = useState(null)

  const projectItems = useMemo(() => {
    if (project?.designExamples?.length) {
      return project.designExamples
    }

    return GROUPS.flatMap((group) => group.items)
  }, [project])

  const groups = useMemo(() => {
    if (project?.designExamples?.length) {
      const grouped = {}

      project.designExamples.forEach((item) => {
        const label = item.group || 'Design examples'

        if (!grouped[label]) {
          grouped[label] = []
        }

        grouped[label].push(item)
      })

      return Object.entries(grouped).map(([label, items]) => ({
        label,
        items,
      }))
    }

    return GROUPS
  }, [project])

  return (
    <section
      ref={ref}
      id={project?.id || '18'}
      className="project-section design-examples-section"
      data-project-id={project?.id || '18'}
      data-section-index={index}
      data-active={isActive ? 'true' : 'false'}
    >
      <div className="design-examples-inner">
        <header className="design-examples-header">
          <div>
            <span className="design-examples-kicker">
              {String(index + 1).padStart(2, '0')} / {String(total).padStart(2, '0')}
            </span>

            <h2>
              {project?.title || 'Print & Editorial Design'}
            </h2>
          </div>

          <div className="design-examples-count">
            {projectItems.length} examples
          </div>
        </header>

        <nav className="design-examples-groups">
          {groups.map((group, i) => (
            <button
              key={group.label}
              type="button"
              className={i === activeGroup ? 'active' : ''}
              onClick={() => setActiveGroup(i)}
            >
              {group.label}
            </button>
          ))}
        </nav>

        <div className="design-examples-grid">
          {(groups[activeGroup]?.items || []).map((item) => (
            <button
              type="button"
              key={item.filename || item.title}
              className="design-example-card"
              onClick={() => setActiveItem(item)}
              style={{
                '--asset-ratio': item.ratio || 1,
              }}
            >
              <span className="design-example-image">
                <img
                  src={item.grid}
                  alt={item.title}
                  loading="lazy"
                />
              </span>

              <span className="design-example-title">
                {item.title}
              </span>
            </button>
          ))}
        </div>
      </div>

      {activeItem && (
        <div
          className="design-example-lightbox"
          role="dialog"
          aria-modal="true"
          onClick={() => setActiveItem(null)}
        >
          <button
            type="button"
            className="design-example-lightbox-close"
            aria-label="Close"
            onClick={() => setActiveItem(null)}
          >
            ×
          </button>

          <img
            src={activeItem.full || activeItem.grid}
            alt={activeItem.title}
            onClick={(event) => event.stopPropagation()}
          />
        </div>
      )}
    </section>
  )
})

export default DesignExamplesSection
